### ISSUE TITLE
Image Register Issue

### ISSUE THREAD

**Issue by Wooseok1114** [BGIResearch/SAW#27]
I used this code

`singularity exec SAW_v5.4.0.sif register \
-i $LOC/image/SS200000154TR_F5_20221124_180305_1.1.3.tar.gz\ 
-c $LOC/image/SS200000154TR_F5_20221124_180305_1.1.3.ipr \
-v $LOC/output/result/02.count/SS200000154TR_F5.raw.gef \
-o $LOC/output/result/03.register/\`

And the result is

I0116 05:42:54.730423 1418 utils.py:145] Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
I0116 05:42:54.730578 1418 utils.py:157] NumExpr defaulting to 8 threads.
I0116 05:42:57.594049 1418 schemas.py:1221] Resource 'XMLSchema.xsd' is already loaded
2023-01-16 05:43:00.863758: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/python3/lib/python3.8/site-packages/cv2/../../lib64:/opt/lib:/.singularity.d/libs
2023-01-16 05:43:00.863809: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
STEREOmics REgistration and SEgmentation Pipeline (STEREO-RESEP)
Namespace(auto_remove=False, chip_id='SS84', conf='/nfs/SCMGL/wsk999_SAW/data/demo/SS200000154TR_F5_tongue/image/SS200000154TR_F5_20221124_180305_1.1.3.ipr', func=<class '__main__.Pipeline'>, input='/nfs/SCMGL/wsk999_SAW/data/demo/SS200000154TR_F5_tongue/image/SS200000154TR_F5_20221124_180305_1.1.3.tar.gz', manufacturer='motic', output='/nfs/SCMGL/wsk999_SAW/data/demo/SS200000154TR_F5_tongue/output/result/03.register/', restart=False, vis='/nfs/SCMGL/wsk999_SAW/data/demo/SS200000154TR_F5_tongue/output/result/02.count/SS200000154TR_F5.raw.gef') []
[INFO 20230116-05-43-06 p1418 prepare_dir main.py:306] Dir preparation completed.
I0116 05:43:06.996938 1418 main.py:306] Dir preparation completed.
[WARN 20230116-05-43-06 p1418 check_files2 main.py:330] The *_transformed.tif image could not be found under the /nfs/SCMGL/wsk999_SAW/data/demo/SS200000154TR_F5_tongue/image/SS200000154TR_F5_20221124_180305_1.1.3.tar.gz.
W0116 05:43:06.998095 1418 main.py:330] The *_transformed.tif image could not be found under the /nfs/SCMGL/wsk999_SAW/data/demo/SS200000154TR_F5_tongue/image/SS200000154TR_F5_20221124_180305_1.1.3.tar.gz.
[INFO 20230116-05-43-08 p1418 prepare_input main.py:382] Extract files from zipped file completed.
I0116 05:43:08.141663 1418 main.py:382] Extract files from zipped file completed.
[INFO 20230116-05-43-08 p1418 pipeline_entry main.py:64] Copy ipr.
I0116 05:43:08.145125 1418 main.py:64] Copy ipr.
[WARN 20230116-05-43-09 p1418 run main.py:152] Pipeline need to handle these subtask: ['cellseg', 'register', 'stitch', 'tissueseg'].
W0116 05:43:09.943819 1418 main.py:152] Pipeline need to handle these subtask: ['cellseg', 'register', 'stitch', 'tissueseg'].
[INFO 20230116-05-43-09 p1418 run main.py:167] >> Next do the stitching task.
I0116 05:43:09.946116 1418 main.py:167] >> Next do the stitching task.
Traceback (most recent call last):
  File "stereo-resep_v2.3.0/stereo-resep-cell_v2.3.0/stereo-resep/main.py", line 689, in <module>
  File "stereo-resep_v2.3.0/stereo-resep-cell_v2.3.0/stereo-resep/main.py", line 24, in __init__
  File "stereo-resep_v2.3.0/stereo-resep-cell_v2.3.0/stereo-resep/main.py", line 122, in pipeline_entry
  File "stereo-resep_v2.3.0/stereo-resep-cell_v2.3.0/stereo-resep/main.py", line 173, in run
  File "stereo-resep_v2.3.0/stereo-resep-cell_v2.3.0/stereo-resep/stitching/stitch.py", line 22, in stitch_entry
  File "stereo-resep_v2.3.0/stereo-resep-cell_v2.3.0/stereo-resep/stitching/fov_stitching/fov_info.py", line 66, in __init__
  File "stereo-resep_v2.3.0/stereo-resep-cell_v2.3.0/stereo-resep/utils/common.py", line 410, in __init__
  File "stereo-resep_v2.3.0/stereo-resep-cell_v2.3.0/stereo-resep/utils/common.py", line 420, in _load_items
AttributeError: module 'Crypto.Cipher.AES' has no attribute 'MODE_EAX'

What do I have to change for fixing this error?

**Comment by Wooseok1114** [comment]
Temporally fixed.
I moved to another server and it works
