### ISSUE TITLE
BlockingIOError: [Errno 11] Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

### ISSUE THREAD

**Issue by Wooseok1114** [BGIResearch/SAW#28]
singularity exec SAW_v5.4.0.sif cellCluster -i /home/guest/041.cellcut/SS200000154TR_F5.cellbin.gef -o /home/guest/051.cellcluster/SS200000154TR_F5.cell.cluster.h5ad

[2023-01-19 17:20:18][Stereo][84735][139776566339392][reader][436][INFO]: Finished output to /home/guest/051.cellcluster/SS200000154TR_F5.cell.cluster.h5ad
Traceback (most recent call last):
  File "/ldfssz1/ST_BI/USER/tianyongjing/singularity/spatial_RNA_visualization_v5.4.0/cellcluster_v1.4.0/cell_cluster.py", line 134, in <module>
  File "/ldfssz1/ST_BI/USER/tianyongjing/singularity/spatial_RNA_visualization_v5.4.0/cellcluster_v1.4.0/cell_cluster.py", line 130, in main
  File "/ldfssz1/ST_BI/USER/tianyongjing/singularity/spatial_RNA_visualization_v5.4.0/cellcluster_v1.4.0/cell_cluster.py", line 76, in impute_cgef
  File "/usr/local/python3/lib/python3.8/site-packages/h5py/_hl/files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/usr/local/python3/lib/python3.8/site-packages/h5py/_hl/files.py", line 222, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
BlockingIOError: [Errno 11] Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

I searched and it is a problem with h5ad file reading without close.
Is it right? and how can I fix it

**Comment by Wooseok1114** [comment]
export HDF5_USE_FILE_LOCKING=FALSE
Above command solved the problem

**Comment by DMaspero** [comment]
Dear SAW developers,

I have the same problem. I tried to set the environment variable HDF5_USE_FILE_LOCKING to false, but I still get the same error.
I am using SAW v.6.0.1.

Could you please help me to figure out how to fix it?
